# Change these first
owner: nlbao # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: nlbao.page
    url: nlbao.page
  - name: nlbao.netlify.app
    url: nlbao.netlify.app
  - name: nlbao.github.io
    url: https://nlbao.github.io
  - name: nlbao-bot.github.io/uptime
    url: https://nlbao-bot.github.io/uptime
  - name: Secret Site
    url: $SECRET_SITE
  - name: anla11.github.io
    url: https://anla11.github.io/
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: nlbao's Upptime
  introTitle: "**Real-time** data from [github.com/nlbao-bot/uptime](https://github.com/nlbao-bot/uptime)"
  introMessage: No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
